language: node_js
node_js:
- node
deploy:
  provider: npm
  email: christopher.andrejewski@gmail.com
  api_key:
    secure: BckHTiJSbymf0y1hXcr3arD36wJoRVFWBLPyhJKAx1uXTvHXGNQ5FFWQeemjrvpg2lO5dFXX0f09DKY3dh7VI9/hUJvebZ6ExvRckYY5eN77Qa/vitRPRhi06zenyZzh61KOAuYFwCuDLugZq9Ap6zBYGqmmxSarUTL9gfN05kIl3+4nVOvv60guV92Q6y1b1aQ377197nnAo1A7zf5qz8PrWAUOzGXg7s078takFZCe1KSwjgEzhx8E0l9RyWbl96+ymCxNPniNSqqAhhin7oNYzrM3lHcCmU+xspoj6n7BhvfQ/nCsLQh2UGFnTGieTXppJW1/Vyhx2XIhPJLwf7IpgFhtKmokUEKMEvz/AsaApSKYTmioftEjmFT0Zg5IG5vUaTIeuyabm0H/gZRBFrA5KihEDXDDvJRvieUGW1lE0XRUUsETY7MZ3HNcQ6M9d5UXaiCwBE1rZGsoLFl3dWOMHBGzYmFwGF/Kkgk38t3s7UIRJkRLGvACXDcbhjaxEOkif5RMxhtCUusAqC8c58IltA9PpQ/fXRYJa3fQ58WSgCG+JY+9FDtylCoPMnq0G5D3MZBBQIodd8ol9N2efxapA0XCJf5feH+3tizg3z0twmDke95MFfBylHgpvR/OsD5bdFci74NsMAtxkFpjYVccMokk27DoF1GsBuG/rPA=
  on:
    tags: true
    repo: andrejewski/testa
  skip_cleanup: true
