language: node_js
node_js:
- node
deploy:
  provider: npm
  email: christopher.andrejewski@gmail.com
  api_key:
    secure: ZpwEgeHlKpdgDfuZ4pYGsw95k3Q2ZIFyVQRG433TTO9XFYJxWXbYqzpWMCrNv//UNBkRGDQbS++Ske1AmyOioktF0CHXrX5ccpfePbzFZ9CZvKx7EBVR+9J+wDkQ1M8mFeag05Wr3AQLyB+rknb2WoGBbx7YFrkdmy+79fZajVCXoJGwZH0pB8NDTJK54UOHC4rMG9tQu/OVGk+iDbiJZUanZEfFixFKgFboroJZ/cz6SHwXzRG08PYaMP7Cgh1MiWj8oXE9mekWh8vK8xO+kc3qDfL5wGPuwNifBT5zc2p+rK4dY0tn0WuWWAcghU3r/0bWbYXpqNCEYfMSMZDaMF982DUALtd2lxwO6/pWIqwDKKKzjLEXn2ozjJD36loX1Dvp5hVZ7mv3Xizi0retWKRxZNqKHW6940w7KZJ787SDFedlV//ujXdBrrwxkGqS7nvsJIldZ8+c/mo/DgWJdADlBI39IT10MQabV2hDugCYWG/3SYPPsTulBJCxr6gokANOZRwnsSVRm4Z6b5QS3DWb1ms6lOrJSsMnGwZDW51kP/wK7J2s+TuZV4zAAXGZsZkzS7+j5H7zGXtS58aWC0gyav+Hs5gFg1w2LqemwI1kYUvaDXj3/FJCICyPE2udNHgXWu4Z8twaKoGp54IQzQuH5pcTJ3ycTYrcHKzyhOY=
  on:
    tags: true
    repo: andrejewski/testa
  skip_cleanup: true